### ISSUE TITLE
As a member of the IAM team, we noticed that Sentinel allows too many people access to the tool.  We need to Restrict and Document the access so we have better security in place.

### ISSUE THREAD

**Issue by info-gaidaros** [stib-mivb-cloud/dcp-project#22]
Need a meeting with Security to refine the request and to understand the needs

We, IAM Team, noticed a “slight” problem with the accesses to Sentinel, which is a highly sensitive tool used by Security.
Today, a lot of people have access to its data and they shouldn’t.
 
Could we organize a meeting during your next sprint to talk about it and see how we can adapt it?
What we would like to do is :
Grant enough access to Security Team to be able to configure the tools themselves
Restrict the access, even in read, to the right people
Make sure the access is correctly documented
 
Let me know when we could meet and talk about this topic.
 
Thanks a lot and have a really nice day,

**Comment by pondichys** [comment]
- Meeting scheduled on 2022-09-01
- Proposition sent to Microsoft contact for Azure Sentinel and positive feedback received.
- Still want to try a last possibility using custom Azure role

**Comment by pondichys** [comment]
Meeting held
What to do with this task next? -> see with Scrum Master and Product Owner

**Comment by VeerleDerdelinckx** [comment]
Meeting minutes - waiting for chosen option by security

**Comment by pondichys** [comment]
Meeting minutes sent
