### ISSUE TITLE
RBAC Issue:  As a Devops Engineer I want to be able to see all pods inside a namespace, therefore I need to get a list of all namespaces.

### ISSUE THREAD

**Issue by VeerleDerdelinckx** [stib-mivb-cloud/dcp-project#72]
Update view clusterrole in aks install > should enable listing the namespaces to which the clusterrole is binded to.

**Comment by Basil-LK** [comment]
Add the following inside stib-project-edit for SSO
```
rules:
	- apiGroups: [""]
	  resources: ["namespaces"]
          verbs:     ["get","list","watch"]
```

**Comment by pondichys** [comment]
I would maybe add it to the cluster view  ... my point is that it would be nice to be able to list the namespaces without specifying option --namespace in the kubectl command

**Comment by pondichys** [comment]
After some tests, looks like we need to investigate deeper than foreseen.

Reason:
- cluster role stib-view-cluster is not bound anymore in new project code -> its functionalities are missing

Actions to discuss to solve that request
- first, ask if this is really needed :)
- if yes then
- modify the stib-view-cluster to add get-list-watch namespace in the az-aksinstall code base
- add a new cluster role binding for stib-view-cluster in new project code
- test if it works
- assess the impact on existing projects
- rerun the project code for all existing projects

Remark: a role binding of a cluster role seems to limit the permissions to namespace scoped resources. To be checked further.

**Comment by info-gaidaros** [comment]
Estimate changed from 3 to 5, due to much more complex.
